export type SkillCategory = {
  name: string;
  skills: string[];
};

export const skillCategories: SkillCategory[] = [
  {
    name: "Development",
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "Python",
      "Django",
      "Vue.js",
      "Angular",
      "PHP",
      "Laravel",
      "Ruby on Rails",
      "Java",
      "Spring Boot",
      "Go",
      "Rust",
      "C#",
      ".NET",
      "Swift",
      "Kotlin",
      "Flutter",
      "React Native",
      "GraphQL",
      "REST APIs",
    ],
  },
  {
    name: "Data & AI",
    skills: [
      "Data Analysis",
      "Data Science",
      "Machine Learning",
      "SQL",
      "PostgreSQL",
      "MongoDB",
      "Data Visualization",
      "Excel (Advanced)",
      "Power BI",
      "Tableau",
      "Python for Data",
      "Statistics",
      "AI Prompt Engineering",
      "Natural Language Processing",
    ],
  },
  {
    name: "Cloud & DevOps",
    skills: [
      "AWS",
      "Google Cloud",
      "Azure",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Terraform",
      "Linux Administration",
      "Cybersecurity",
      "Network Security",
      "DevOps",
      "Site Reliability Engineering",
    ],
  },
  {
    name: "Design",
    skills: [
      "Figma",
      "UI Design",
      "UX Design",
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Graphic Design",
      "Motion Design",
      "Product Design",
      "Wireframing",
      "Design Systems",
      "Branding",
      "Video Editing",
    ],
  },
  {
    name: "Business & Marketing",
    skills: [
      "Digital Marketing",
      "SEO",
      "Content Marketing",
      "Social Media Management",
      "Copywriting",
      "Email Marketing",
      "Paid Ads (Google/Meta)",
      "Market Research",
      "Business Analysis",
      "Sales",
      "CRM Management",
      "Bookkeeping",
      "Accounting",
      "Financial Modeling",
    ],
  },
  {
    name: "Writing & Translation",
    skills: [
      "Technical Writing",
      "Content Writing",
      "Editing & Proofreading",
      "Translation",
      "Transcription",
      "Grant Writing",
      "Scriptwriting",
    ],
  },
  {
    name: "Soft Skills",
    skills: [
      "Communication",
      "Project Management",
      "Team Leadership",
      "Problem Solving",
      "Time Management",
      "Client Management",
      "Agile / Scrum",
      "Critical Thinking",
      "Adaptability",
      "Negotiation",
      "Mentoring",
      "Cross-functional Collaboration",
    ],
  },
  {
    name: "Non-Digital / Trade Skills",
    skills: [
      "Carpentry",
      "Plumbing",
      "Electrical Work",
      "Tailoring",
      "Event Planning",
      "Photography",
      "Interior Design",
      "Culinary Arts",
      "Construction Management",
      "Agriculture",
    ],
  },
];

export const allSkills: string[] = skillCategories.flatMap((c) => c.skills);
